### ISSUE TITLE
tf.Exception thrown while using waitForTransform when a frame doesn't exist

### ISSUE THREAD

**Issue by marcoesposito1988** [ros/geometry2#102]
As reported by other users as well in http://answers.ros.org/question/207039/tfexception-thrown-while-using-waitfortransform a bug seems to have appeared when using TF.

waitForTransform throws a tf.Exception if one of the frames doesn't exist yet (which is actually the point of waitForTransform).

It must be a bug in TF2. When I checked out geometry 1.11.4 the bug was still there, but when I also checked out geometry-experimental 0.5.7 the bug disappeared.

 Any idea about the reason?

**Comment by sklaw** [comment]
Here are the combinations of TF and TF2 I've found so far that will cause this problem: 
TF 1.11.6 with TF2 0.5.9
TF 1.11.6 with TF2 0.5.8

TF 1.11.4 with TF2 0.5.9
TF 1.11.4 with TF2 0.5.8

**Comment by tfoote** [comment]
What is the exception thrown? I added unit tests for wait for transform, in https://github.com/ros/geometry/commit/9624370b2327480ee429c5671455e3880825d256

**Comment by tfoote** [comment]
Related questions on answers.ros.org
- http://answers.ros.org/question/207582/does-tflookuptransform-python-take-time-to-fire-up/
- http://answers.ros.org/question/207052/rospy-tf-waitfortransform-not-waiting/

**Comment by tfoote** [comment]
I believe I've found the issue in this commit: https://github.com/ros/geometry_experimental/commit/2f5ba1db9c86043221d49d25683cb2ef82211f1e

When running inside rospy, the roscpp client is not initialized and thus ros::ok is false. I'm going to have to think about how to make this work cleanly in both roscpp and rospy. .

**Comment by tfoote** [comment]
This should be fixed in geometry_experimental 0.5.11
