### ISSUE TITLE
rviz tf display tool does not handle static transforms correctly

### ISSUE THREAD

**Issue by davetcoleman** [ros/geometry2#108]
Seems to me static transforms should always display in Rviz, but instead they fade out as if they were non-static. Resetting the tf display makes the transform show again until the "Frame Timeout" is reached. Thoughts?

**Comment by tfoote** [comment]
The rviz display needs to be updated to know the difference between regular and static transforms. For efficiency static_transforms are now published as latched topics. The gray out logic in rviz's display does not take that into account. This should be filed against the rviz tf plugin.

**Comment by davetcoleman** [comment]
Sure, i just thought the issue would be seen by the right person (you) on this issue tracker

https://github.com/ros-visualization/rviz/issues/888

**Comment by tfoote** [comment]
Yeah, thanks for refiling.
