### ISSUE TITLE
canTransform does not reset error string when it just times out

### ISSUE THREAD

**Issue by stwirth** [ros/geometry2#117]
I am using this little function to wait for a tf to become available:

``` C++
/**
 * Blocks for the tf from->to to become available.
 */
inline bool waitForTf(const tf2_ros::Buffer &tf2_buffer, const std::string &from, const std::string& to)
{
  std::string err;
  while (ros::ok() && !tf2_buffer.canTransform(from, to, ros::Time(0), ros::Duration(1.0), &err)) {
    ROS_INFO_STREAM("Waiting for transform " << from << "->" << to << " to be available. (tf says: " << err << ")");
  }
}
```

When the required transform does not become available, after some time I get errors like this:

```
[ INFO] [1438933887.448176468]: Waiting for transform map->base_link to be available. (tf says: . canTransform returned after 1.00534 timeout was 1.. canTransform returned after 1.0094 timeout was 1.. canTransform returned after 1.00617 timeout was 1.. canTransform returned after 1.00913 timeout was 1.. canTransform returned after 1.00304 timeout was 1.. canTransform returned after 1.00011 timeout was 1.. canTransform returned after 1.00064 timeout was 1.. canTransform returned after 1.00281 timeout was 1.. canTransform returned after 1.00711 timeout was 1.. canTransform returned after 1.00703 timeout was 1.. canTransform returned after 1.00794 timeout was 1.. canTransform returned after 1.00724 timeout was 1.. canTransform returned after 1.00759 timeout was 1.. canTransform returned after 1.00654 timeout was 1..)
```

That is caused by `err` not being reset to an empty string in `canTransform`. [The message is only appended](https://github.com/ros/geometry_experimental/blob/fccbbd2675e76fc80eff7d46628ef2f74999ae16/tf2_ros/src/buffer.cpp#L104-L114). If an actual error is detected in canTransform, the error message is assigned to err_str (e.g. [here](https://github.com/ros/geometry_experimental/blob/fccbbd2675e76fc80eff7d46628ef2f74999ae16/tf2_ros/src/buffer.cpp#L177)).
I would propose to make this consistent by setting `err_str` to an empty string in the beginning of `Buffer::canTransform`.

**Comment by tfoote** [comment]
That seems reasonable for this use case. However the append behavior is not an accident. I believe there are cases where the error passes through a layer or two and the appending behavior is the only way to get the inside error message out.
