### ISSUE TITLE
Invalid argument "/any_frame" passed to canTransform argument source_frame in tf2 frame_ids cannot start with a '/'

### ISSUE THREAD

**Issue by hershwg** [ros/geometry2#12]
The warning message on line 139 of src/buffer_core.cpp prints thousands of times per second in my program (rviz) in hydro because all the sensor data has frame_id values that start with "/", which is incorrect as of today.

I can remove it from things where the source of the frame_ids is rviz, like the gui and config files, but all the sensor data is processed by tf::MessageFilter<MessageType> templates.  Do I really need to change all my sensor driver code to remove the / before this will quiet down?

**Comment by tfoote** [comment]
I've got a patch pending which will clean this up before it is passed to tf2 from tf.  If you call tf2 directly you will need to sanitize.

**Comment by tfoote** [comment]
@hershwg can you check that my patches in 1.10.3 of geometry work now?

**Comment by hershwg** [comment]
Sorry that I didn't check this sooner.

Actually there is a pretty major bug: if you call `resolve("/map")` you
get back the empty string.

You need to change `erase(0)` to `erase(0,1)` in
`strip_leading_slash()`.  The second argument to string::erase() is the
number of characters to erase, which defaults to all of them.

I'm surprised the tests didn't catch this.  Maybe they aren't being run?

Dave

**Comment by hershwg** [comment]
The above comments refer to file `tf/src/tf.cpp`.

**Comment by tfoote** [comment]
fixed erase syntax 37e978f94fab27e2e5596e96e7f3b675581a22e3
