### ISSUE TITLE
Bad import in tf2_sensor_msgs.py

### ISSUE THREAD

**Issue by peci1** [ros/geometry2#121]
In tf2_sensor_msgs.py, line 32:

```
from sensor_msgs.point_cloud2 import read_cloud
```

However, there's no `read_cloud` method in sensor_msgs.point_cloud2 (both in indigo-devel and jade-devel). There's however a similar method called `read_points` there. Did you mean this one?

This also means (and I've checked it) there's a missing Python test.

**Comment by tfoote** [comment]
Fixed in #119
