### ISSUE TITLE
compiler warning on Windows

### ISSUE THREAD

**Issue by dirk-thomas** [ros/geometry2#149]
http://ci.ros2.org/view/packaging/job/packaging_windows/103/warnings34Result/

**Comment by tfoote** [comment]
all but 2 of these are resolved in #153 

The one remaining one is ctime vs ctime_s, it will take a few hours to figure out how to best work around that. The current fix moved from ctime being an issue to localtime which has the same unix/windows dichotomy of available methods despite it supposed to be a standard.

**Comment by tfoote** [comment]
last part in #154
