### ISSUE TITLE
tf2_buffer_server doesn't set up action server properly.

### ISSUE THREAD

**Issue by ahendrix** [ros/geometry2#15]
Whenever the tf2 buffer server starts, it prints the following warning:

```
[ WARN] [1373931844.009500433]: You've passed in true for auto_start for the C++ action server at [/tf2_buffer_server]. You should always pass in false to avoid race conditions.
```

**Comment by wasowski** [comment]
Isn't this the same issue as https://github.com/ros/geometry2/issues/9 that has been fixed in PR https://github.com/ros/geometry2/pull/10 ? Shouldn't it be closed to avoid pollution in the issue tracker? :) Or does the problem persist?

**Comment by tfoote** [comment]
Thanks I believe that you're right that it's double reported likely before the update had propogated as it's only a week after the issue was closed.
