### ISSUE TITLE
[ros2] Executables build only for default RMW implementation

### ISSUE THREAD

**Issue by gerkey** [ros/geometry2#169]
Tools like `tf2_echo` and `static_transform_publisher` are built only for the default RMW implementation. Is that intended, or should we be building for all of them at this point?

**Comment by tfoote** [comment]
We only want to be building multi-rmw targets to validate cross rmw verification. The assumption is that above rcl, packages should be rmw unaware.

**Comment by gerkey** [comment]
Makes sense to me.
