### ISSUE TITLE
BufferCore::canTransform does not fill error_msg in case frame_ids are not found

### ISSUE THREAD

**Issue by ce047** [ros/geometry2#198]
Using `tf2::BufferCore::canTransform` with non-existing frame_ids correctly returns `false` but ignores the given error_msg:

```cpp
  tf2::BufferCore bf;
  std::string error_msg("Error msg: ");
  if (!bf.canTransform("not", "existing", ros::Time(0.0), &error_msg))
  {
    ROS_ERROR_STREAM("Cannot transform! " << error_msg); // error msg stays untouched
  }
```
prints the following:
```
[ERROR] [1484048173.537888898]: Cannot transform! Error msg: 
```

**Comment by tfoote** [comment]
Indeed. It doesn't appear to have any logic for populating the error message in any version of the method at that level.
