### ISSUE TITLE
New Release for indigo et al. 

### ISSUE THREAD

**Issue by DLu** [ros/geometry2#199]
http://answers.ros.org/question/251554/import-tf2statictransformpublisher-in-python/

Please.

**Comment by tfoote** [comment]
There's a new release coming soon. I just finished triaging PRs in the last week.

**Comment by tfoote** [comment]
0.5.15 should be in the next syncs

**Comment by DLu** [comment]
Did it sync yet? http://repositories.ros.org/status_page/ros_indigo_default.html?q=geometry2&s=2
