### ISSUE TITLE
tf2 introduction

### ISSUE THREAD

**Issue by tkruse** [ros/geometry2#20]
I looked over the tf2 documentation, in particular the migration guide: http://www.ros.org/wiki/tf2/Migration and there are several things that seem weird to me.

If tf was really depreated in favour of tf2, then the tf wiki page and tutorials should say so.

geometry_experimental is not a good name for the thing to be used (was not a future proof name).

Several cripts like tf_echo seem to still only exist in package tf. While I generally like that, maybe the migration guide could mention that this is where scripts shall live. And then this should also be the place for other scripts (I'd love to have all tf scripts in one package, so that tab completion can help me remember the name of a script).

There is still both tf/view_frames and tf2_tools/view_frames, seemingly doing the same thing, only the tf one seems to be installed, but hydro also install tf2_tools, consisting of nothing else then view_frames. In a groovy devel space, one can rosrun tfw/view_frames.py /though not in a groovy install).

The same goes for tf/static_transform_publisher and tf2_ros/static_transform_publisher, why have 2 of them?

[EDIT: Removed text, several static latching publishers are no problem, sorry]

The migration wiki pages speaks of an "Action Based Query", but does not point at a resource where this can be found. (Also I have no clue why anyone would want to send a tf query as an action rather than a service).

http://www.ros.org/wiki/tf2 mentions: "tf2_ros also provides rospy bindings for tf2" I assume this has to be changed for Hydro, saying thos bindings in hydro are in tf2_py?

**Comment by tkruse** [comment]
Hm, maybe the part in http://www.ros.org/wiki/tf2/Migration saying "In Hydro tf has been deprecated in favor of tf2." should be removed, given the state of the tutorials and that no package yet seems to use tf2 in C++.

**Comment by jack-oquin** [comment]
Any chance of getting these problems fixed? They are still broken.

See also: #52

**Comment by jbohren** [comment]
Additionally all the functions that transform twists in BufferCore are still commented out.

**Comment by tkruse** [comment]
Possibly the wiki could at least warn users that the tutorials are outdated, in order to prevent scaring off new users.

**Comment by jack-oquin** [comment]
+1  

I wasted a couple of hours yesterday trying to figure out how to use `tf2` for a simple task, only to discover that the documentation is wrong, contradictory and confusing. `tf2_ros` has no Python API docs at all. I finally gave up on `tf2`, and got the job done using `tf` in no time at all.

If I had known `tf2` is not yet ready for general use, I would not have wasted all that time.

**Comment by bchretien** [comment]
@jack-oquin: :+1: I just had the same experience.

As @tkruse said, saying that `tf` is deprecated in favor of `tf2` is really misleading since the documentation is either wrong or missing.

**Comment by jack-oquin** [comment]
I added this to the http://wiki.ros.org/tf2/Migration page:

> Unfortunately, the tf2 documentation for Hydro is incomplete (issue #20). Until that issue has been resolved, most users will have better luck using the older tf interfaces, which are still supported, better documented, and implemented using tf2 under the covers.

There may be other wiki pages that could use similar warnings. I linked it to this issue so people will know when it has been resolved.

**Comment by athoesen** [comment]
Wow.  You literally just saved me hours and hours of frustration which I cannot afford at the moment.  Thank you @jack-oquin .  So I was about to start the tf2 tutorials and now I'm seeing this is a terrible idea and I should just stick with tf in Hydro?

**Comment by jack-oquin** [comment]
That is my opinion. Your experience may differ.

As best I can tell, tf2 works fine in Hydro, but some documentation is missing, and some of what exists seems to be wrong. The old tf still works, and looks like a reasonable alternative until someone with the requisite knowledge straightens out the tf2 docs.

**Comment by tfoote** [comment]
The tutorials have been updated, and I've added links to action based examples. The installation issues were resolved a while ago. If there's anything more specific please open individual tickets.
