### ISSUE TITLE
tf chaining broken on pr2

### ISSUE THREAD

**Issue by ahendrix** [ros/geometry2#22]
Originally filed by @tkruse  at: https://code.ros.org/trac/wg-ros-pkg/ticket/5176

Hi, using latest apt-get electric on lucid on the PR2, I do:

```
$ roscore
```

Just to make sure no overlays are used

```
$ export ROS_PACKAGE_PATH=/opt/ros/electric/stacks
$ roslaunch /etc/ros/robot.launch
...
$ rosrun tf tf_monitor /base_link /r_elbow_flex_link
...
RESULTS: for /base_link to /r_elbow_flex_link
Chain is: /base_link -> /base_footprint -> /odom_combined -> /base_link -> /sensor_mount_link -> /head_plate_frame -> /head_tilt_link -> /head_pan_link -> /sensor_mount_link -> /high_def_frame -> /torso_lift_link -> /base_link -> /l_forearm_roll_link -> /l_elbow_flex_link -> /l_forearm_cam_frame -> /l_forearm_roll_link -> /l_gripper_palm_link -> /l_wrist_roll_link -> /l_gripper_palm_link -> /l_wrist_flex_link -> /l_gripper_palm_link -> /torso_lift_link -> /l_upper_arm_roll_link -> /l_shoulder_lift_link -> /laser_tilt_mount_link -> /torso_lift_link -> /double_stereo_link -> /narrow_stereo_link -> /narrow_stereo_gazebo_l_stereo_camera_frame -> /narrow_stereo_gazebo_l_stereo_camera_frame -> /narrow_stereo_gazebo_r_stereo_camera_frame -> /narrow_stereo_link -> /projector_wg6802418_frame -> /head_plate_frame -> /r_forearm_roll_link -> /r_elbow_flex_link -> /r_forearm_cam_frame -> /r_forearm_roll_link -> /r_gripper_palm_link -> /r_wrist_roll_link -> /r_gripper_palm_link -> /r_wrist_flex_link -> /r_gripper_palm_link -> /torso_lift_link -> /r_upper_arm_roll_link -> /r_shoulder_lift_link -> /double_stereo_link -> /wide_stereo_link -> /wide_stereo_gazebo_l_stereo_camera_frame -> /wide_stereo_gazebo_l_stereo_camera_frame -> /wide_stereo_gazebo_r_stereo_camera_frame -> /wide_stereo_link -> NO_PARENT -> /bl_caster_rotation_link -> /base_link -> /bl_caster_rotation_link -> /br_caster_rotation_link -> /base_link -> /br_caster_rotation_link -> /fl_caster_rotation_link -> /base_link -> /fl_caster_rotation_link -> /fr_caster_rotation_link -> /base_link -> /fr_caster_rotation_link -> /torso_lift_link -> /l_upper_arm_link -> /l_gripper_r_finger_tip_link -> /l_gripper_r_finger_link -> /l_gripper_palm_link -> /l_gripper_l_finger_link -> /l_gripper_motor_slider_link -> /l_gripper_palm_link -> /l_gripper_palm_link -> /l_shoulder_pan_link -> /torso_lift_link -> /l_forearm_link -> /r_upper_arm_link -> /r_gripper_r_finger_tip_link -> /r_gripper_r_finger_link -> /r_gripper_palm_link -> /r_gripper_l_finger_link -> /r_gripper_motor_slider_link -> /r_gripper_palm_link -> /r_gripper_palm_link -> /r_shoulder_pan_link -> /torso_lift_link -> /r_forearm_link -> /base_link
...
```

I also tend to get other tf problems within my custom nodes, but I guess they relate to this original problem.

I don't even know where to start looking for the cause (tf, URDF, some standard node?).

Also not sure whether to report this to pr2 support instead. But the same happens for e.g.:

```
$ roslaunch pr2_gazebo pr2_empty_world.launch
$ rosrun tf tf_monitor /torso_lift_link /r_gripper_palm_link
```

**Comment by ahendrix** [comment]
Done for Gazebo launch. Though I would hope that was unnecessary, hoping it is easy for you to reproduce.

Anyway, it seems the cause is not too mysterious: in `tf.cpp:Transformer::chainAsVector(const std::string & target_frame, ros::Time target_time, const std::string & source_frame, ros::Time source_time, const std::string& fixed_frame, std::vector<std::string>& output) const`

None of the input parameters other than output are even being used, this is makred as //@todo. The code that worked in diamondback is still in tf.cpp, but commented out.

For my other problems, it seems I cannot reproduce, maybe there was something wrong with my waitForTransform at the time.

**Comment by ahendrix** [comment]
@ahendrix: Obsolete with the use of tf2 as the backend for tf. Closing.

@tkruse: I beg to differ. Not only is tf still there and the tf_monitor script part of it, but also tf2/src/buffer_core.cpp:BufferCore::_chainAsVector is a copy&paste implementation (sigh) of tf/src/tf.cpp:Transformer::chainAsVector.

I would prefer you to reopen the issue, and then close it once that either the tf_monitor script is not part of a ROS distro anymore, or until the tf_monitor script delivered with a distro does not have that problem anymore (e.g. by relying on a fixed tf2 implementation of chainAsVector), please.

**Comment by tfoote** [comment]
This method was stubbed out when the datastructure was converted and currently lists the parent frames not the spanning set.  It needs to be fixed in both implementations.  Fortunately this problem is only in the chainAsVector methods which are used for console output. But it needs to be fixed in both tf and tf2.

**Comment by jackieokay** [comment]
Proposed solution in [pull request 95](https://github.com/ros/geometry_experimental/pull/95). @tkruse and @ahendrix : feel free to review.
