### ISSUE TITLE
tf2_ros::Buffer::canTransform() does not abort on node shutdown

### ISSUE THREAD

**Issue by meyerj** [ros/geometry2#26]
I just had a problem with tf in ROS hydro similar to the one described in [#4882](https://code.ros.org/trac/ros-pkg/ticket/4882) on code.ros.org 2 years ago.

`tf::waitForTransform()` stays in an endless loop and nodes do not shutdown properly if simulated time has been paused. The function seems to use `tf2_ros::Buffer::canTransform()` ([buffer.cpp:87ff](https://github.com/ros/geometry_experimental/blob/d5eba175bacb3bedb64b1ed9f8970f2161fa473e/tf2_ros/src/buffer.cpp#L87)) with a timeout internally without checking `ros::ok()`, therefore posting it here.

**Comment by jbohren** [comment]
This has also been observed and reported on ros-answers: http://answers.ros.org/question/182811/bug-or-intended-behaviour-transformlistenerwaitfortransform-does-not-poll-rosok/?answer=182844#post-id-182844
