### ISSUE TITLE
Is there tf2 version of tf::messageFilter?

### ISSUE THREAD

**Issue by furushchev** [ros/geometry2#277]
As far as I briefly look for codes in this repository, there is no functionality for `tf::messagefilter` for tf2.
Is there any reason that there is no such function migrated from tf? Is it just waiting for contribution?

**Comment by tfoote** [comment]
It's in the tf2_ros package since it's a ROS message filter: See:http://docs.ros.org/lunar/api/tf2_ros/html/c++/classtf2__ros_1_1MessageFilter.html

**Comment by furushchev** [comment]
Oh, there is, I overlooked... Thank you very much anyway!!
