### ISSUE TITLE
Static Transform Broadcaster keeps incomplete list of transforms

### ISSUE THREAD

**Issue by chadrockey** [ros/geometry2#28]
https://github.com/ros/geometry_experimental/blob/hydro-devel/tf2_ros/src/static_transform_broadcaster.cpp#L60

Shouldn't this compare both header.frame_id AND child_frame_id?  As I see it now, it would be possible to have two static transforms, one from parent -> child and one from parent -> step_child.  However, only one of these would make it through this check and be published.

Any inner implementation details I'm missing?  @tfoote

**Comment by tfoote** [comment]
I think it should only be the child_frame_id actually.  Both will have the same parent but that is fine.  And to enable "reparenting" the parent should not be in the comparison.

**Comment by chadrockey** [comment]
Yup, I think you're right,  I made a pull request and added a test for this case:

https://github.com/ros/geometry_experimental/pull/29
