### ISSUE TITLE
tf2_ros/Buffer::canTransform: timout smaller than 10ms are not possible

### ISSUE THREAD

**Issue by cwecht** [ros/geometry2#281]
Currently, `Buffer::canTransform`'s timeout is implemented by polling with a cycle of 0.01ms. Therefore shorter timeouts than 0.01ms are not possible.

I would like to suggest that, if `time_ou`t < 0.01ms, the polling-cycle should be adapted. 

At least, if not changed, this behavior should be documented anywhere...

**Comment by tfoote** [comment]
Yeah, that is a magic number that should be cleaned up. It might make sense to actually pick the sleep period in relation to the timeout in general, something like 100th of the timeout. The rate of polling needs to be traded off against performance. At the low end it will end up saturating at the minimum sleep period. And at the high end it would cause ~100 calls per timeout consistently.
