### ISSUE TITLE
python3 can't import tf

### ISSUE THREAD

**Issue by Acmece** [ros/geometry2#293]
Refer to [#259](https://github.com/ros/geometry2/issues/259)
Follow by @randoms , I start from scratch
```
mkdir catkin_ws
cd catkin_ws
mkdir src
cd src 
git clone https://github.com/ros/geometry
git clone https://github.com/ros/geometry2
cd ..
virtualenv -p /usr/bin/python3 venv
source venv/bin/activate
pip install catkin_pkg pyyaml empy rospkg numpy
catkin_make
source devel/setup.bash
```
However:
**1)** It clones from `melodic-devel` and I ran into some build errors:
```
[ 75%] [ 77%] [ 79%] Building CXX object geometry2/tf2/CMakeFiles/tf2.dir/src/cache.cpp.o
Building CXX object geometry2/tf2/CMakeFiles/tf2.dir/src/buffer_core.cpp.o
Building CXX object geometry2/tf2/CMakeFiles/tf2.dir/src/static_cache.cpp.o
/home/acmece/test/src/geometry2/tf2/src/buffer_core.cpp: In member function ‘bool tf2::BufferCore::warnFrameId(const char*, const string&) const’:
/home/acmece/test/src/geometry2/tf2/src/buffer_core.cpp:126:49: error: ‘CONSOLE_BRIDGE_logWarn’ was not declared in this scope
     CONSOLE_BRIDGE_logWarn("%s",ss.str().c_str());
........
.......
make[2]: *** [geometry2/tf2/CMakeFiles/tf2.dir/src/buffer_core.cpp.o] Error 1
make[1]: *** [geometry2/tf2/CMakeFiles/tf2.dir/all] Error 2
make: *** [all] Error 2
Invoking "make -j4 -l4" failed
```
(actually, I change to clone `indigo-devel` and it can be successfully built)

**2)** Alough I built `indigo-devel` and set up an python3 virtual environment, I still cannot import tf with python3
```
-- Found PythonInterp: /home/acmece/catkin_ws/venv/bin/python (found version "3.4.3") 
-- Using PYTHON_EXECUTABLE: /home/acmece/catkin_ws/venv/bin/python
......
......
-- +++ processing catkin package: 'tf2_py'
-- ==> add_subdirectory(geometry2/tf2_py)
-- Using these message generators: gencpp;genlisp;genpy
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython2.7.so (found suitable version "2.7.6", minimum required is "2") 
```
It seem that I have to use `/opt/ros/indigo/lib/python2.7` as long as I source `/opt/ros/indigo/setup.bash` in order to use `catkin_make`

I am a freshman of this feild. Any help will be greatly appreciated.

**Comment by mikaelarguedas** [comment]
this looks very similar to https://github.com/ros/geometry2/issues/259#issuecomment-368537754
did you try installing python3-dev ?

**Comment by Acmece** [comment]
@mikaelarguedas I did have installed python3-dev.
```
>>> import sys
>>> sys.path
['', '/opt/ros/indigo/lib/python2.7/dist-packages',
 '/home/acmece/catkin_ws/venv/lib/python3.4', 
'/home/acmece/catkin_ws/venv/lib/python3.4/plat-x86_64-linux-gnu', 
'/home/acmece/catkin_ws/venv/lib/python3.4/lib-dynload', 
'/usr/lib/python3.4', 
'/usr/lib/python3.4/plat-x86_64-linux-gnu', 
 '/home/acmece/catkin_ws/venv/lib/python3.4/site-packages']
```
I don't know how to delet this path `'/opt/ros/indigo/lib/python2.7/dist-packages'`
You know, if I didn't source `/opt/ros/indigo/setup.bash`, I can't use `catkin_make` commond.

**Comment by tfoote** [comment]
>You know, if I didn't source /opt/ros/indigo/setup.bash, I can't use catkin_make commond.

If you're creating a python 3 environment you cannot use the system installed versions of any of the python tools including `catkin_make` you must use a version from inside your workspace. See http://wiki.ros.org/Installation/Source for an example of how to invoke `catkin_make_isolated` with the path to the version inside your workspace.

**Comment by tfoote** [comment]
If you need more help getting this going. Please ask a question on answers.ros.org and make sure to link here as well as describing your question in full.

**Comment by whitecoffee** [comment]
I get the same problem as you, have u resolved it yet?

**Comment by tfoote** [comment]
@whitecoffee you cannot mix python2 and python3. If you need more help please ask a question on answers.ros.org with full instructions how to reproduce your problem.
