### ISSUE TITLE
Tf2 Tests Calls BufferCore API in Reverse

### ISSUE THREAD

**Issue by chadrockey** [ros/geometry2#30]
https://github.com/ros/geometry_experimental/blob/hydro-devel/test_tf2/test/buffer_core_test.cpp#L660

This calls the function mBC.lookupTransform(SOURCE, TARGET....);

Whereas the API is:
https://github.com/ros/geometry_experimental/blob/hydro-devel/tf2/src/buffer_core.cpp#L517

lookupTransform(TARGET, SOURCE,....)

This probbably isn't a big deal as long as the tests are consistent within themselves, but it is a little disorienting.

**Comment by tfoote** [comment]
It's ok, that's the difference between referring to transforming a frame or a point in the frame. In the test the variable names are transforming a coordinate frame, all the APIs refer to transforming the data. The result is the inverse.
