### ISSUE TITLE
transformMsgToTF2() and transformTF2ToMsg() declarations missing in buffer_core.h

### ISSUE THREAD

**Issue by jurapura** [ros/geometry2#303]
Functions transformMsgToTF2() and transformTF2ToMsg() defined in buffer_core.cpp are not declared in buffer_core.h header. Therefore, even when the buffer_core.h is included, the functions cannot be found. 
Is there any specific reason why the declarations are missing in the header?

To solve that issue I declared the functions in my library by adding:
```
namespace tf2 {
void transformMsgToTF2(const geometry_msgs::Transform &msg,
                       tf2::Transform &tf2);
void transformTF2ToMsg(const tf2::Transform &tf2,
                       geometry_msgs::TransformStamped &msg, ros::Time stamp,
                       const std::string &frame_id,
                       const std::string &child_frame_id);
}
``` 

This solution works. However, I believe it would be more elegant to put the declarations in the buffer_core.h file.

**Comment by tfoote** [comment]
Those methods are not in the public API which is why they're only in the implementation. 
You can use the tf2::convert API described http://wiki.ros.org/tf2/Tutorials/Migration/DataConversions 
With the implmentation in tf2_geometry_msgs. http://wiki.ros.org/tf2_geometry_msgs
