### ISSUE TITLE
transforming PoseStamped in Python eats RAM

### ISSUE THREAD

**Issue by mgrrx** [ros/geometry2#304]
We noticed that doing many transformations of a PoseStamped in Python eats up RAM. Minimum working example:

    import genpy
    import tf2_ros
    import tf2_geometry_msgs
    import geometry_msgs.msg

    def main():
        p = geometry_msgs.msg.PoseStamped()
        p.header.frame_id = 'map'

        t = geometry_msgs.msg.TransformStamped()
        t.header.frame_id = 'map'
        t.child_frame_id = 'base_link'
        t.transform.rotation.w = 1.0

        tf_buffer = tf2_ros.Buffer(debug=False)
        tf_buffer.set_transform_static(t, 'test')

        do_transform = tf_buffer.registration.get(type(p))
        transform = tf_buffer.lookup_transform('map', 'base_link', genpy.Time(0))
        while True:
            do_transform(p, transform)

    if __name__ == '__main__':
        main()

Let this run for a few seconds and you can see that RAM is eaten up. PR will follow in a bit.

**Comment by tfoote** [comment]
Thanks for the simple script to reproduce the issue. I can confirm that I see the memory growth from running this script.
