### ISSUE TITLE
default duration in TimeCache

### ISSUE THREAD

**Issue by csukuangfj** [ros/geometry2#315]
https://github.com/ros/geometry2/blob/7ea64d25a0631fe91bd277e0d9195f18cc437151/tf2/include/tf2/time_cache.h#L99-L101
The comment `default value of 10 seconds storage ` says it saves a duration of 10 seconds, but
the value `1ULL * 1000000000LL` is 1 second, i.e., there are only 9 zeros, not 10 zeros.

**Comment by tfoote** [comment]
Fixed in #317
