### ISSUE TITLE
translation should be of type Quaternion

### ISSUE THREAD

**Issue by christian-rauch** [ros/geometry2#324]
I get the confusing (but funny) error message: `translation should be of type Quaternion`.

This comes from a copy&paste error in `checkRotationType`:
https://github.com/ros/geometry2/blob/b516a8a470fad31f92884ea1c69f7f8db2713f0d/tf2_py/src/tf2_py.cpp#L408-L420
which should report `rotation should be of type Quaternion`, I assume.

**Comment by tfoote** [comment]
Thanks yes, that's a copy and paste error PR in #325
