### ISSUE TITLE
Faulty doTransform for geometry_msgs::Vector3 

### ISSUE THREAD

**Issue by johuber** [ros/geometry2#330]
The code for transforming a vector does not apply the translation but only rotation.
```
/** \brief Apply a geometry_msgs TransformStamped to an geometry_msgs Vector type.
 * This function is a specialization of the doTransform template defined in tf2/convert.h.
 * \param t_in The vector to transform, as a Vector3 message.
 * \param t_out The transformed vector, as a Vector3 message.
 * \param transform The timestamped transform to apply, as a TransformStamped message.
 */
template <>
inline
  void doTransform(const geometry_msgs::Vector3& t_in, geometry_msgs::Vector3& t_out, const geometry_msgs::TransformStamped& transform)
  {
    tf2::Transform t;
    fromMsg(transform.transform, t);
    tf2::Vector3 v_out = t.getBasis() * tf2::Vector3(t_in.x, t_in.y, t_in.z);
    t_out.x = v_out[0];
    t_out.y = v_out[1];
    t_out.z = v_out[2];
  }
```
The line performing the transformation must be changed to:
```
    tf2::Vector3 v_out = t * tf2::Vector3(t_in.x, t_in.y, t_in.z);
```
Like this it will use the overloaded operator* of transform and properly transform the vector.

**Comment by johuber** [comment]
I just found out it seems to be intended like this, according to issue #124
It is fairly misleading though and could also be mentioned in the function description.

**Comment by tfoote** [comment]
This is intentional Vector and Points have different semantic meanings, that's why they have different classes. This difference is the primary one, they have magnitude and direction but are always from the origin.
