### ISSUE TITLE
errors in tf2_tool view_frames.py

### ISSUE THREAD

**Issue by weiyuhe** [ros/geometry2#338]
Whenever I tried to run view_frames.py. I got this:

[INFO] [1540708524.139129]: Listening to tf data during 5 seconds...
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/tf2_tools/view_frames.py", line 81, in <module>
    main()
  File "/opt/ros/kinetic/lib/tf2_tools/view_frames.py", line 44, in main
    buffer = tf2_ros.Buffer()
AttributeError: 'module' object has no attribute 'Buffer'

I am using Ubuntu 16.04 and ROS Kinetic. Am I the only one have this problem?

**Comment by tfoote** [comment]
Please don't multiply post questions: https://answers.ros.org/question/306904/tf2-error-attributeerror-module-object-has-no-attribute-buffer/ following our support guildelines. https://wiki.ros.org/Support
