### ISSUE TITLE
Jump back in time warning

### ISSUE THREAD

**Issue by zzv2** [ros/geometry2#347]
After upgrading to the newest release `0.5.19` for ROS `kinetic` this warning keeps printing:
`Detected jump back in time of 0.000085s. Clearing TF buffer.`

This is not a clock synchronization issue as I have updated the clocks using chrony. The warning also only started to appear immediately after I upgraded the `tf` package.

I think it might have something to do with this new commit:
https://github.com/ros/geometry2/commit/1c7613532fb1c7df149d2894847abb73c0ac7001

**Comment by zzv2** [comment]
This seems to be related to https://github.com/ros/geometry2/issues/341

**Comment by tfoote** [comment]
This issue was resolved in #344 released in in 0.5.20 which is available on all platforms.

**Comment by zzv2** [comment]
@tfoote It works now, thanks!
