### ISSUE TITLE
Including not existing directory "src/bt" in tf2

### ISSUE THREAD

**Issue by marco-tranzatto** [ros/geometry2#351]
Hi all,

I think [this line](https://github.com/ros/geometry2/blob/melodic-devel/tf2/CMakeLists.txt#L14) of tf2/CMakelists.txt is including a non existing directory ("src/bt").
If you agree with this, I'm happy to open a PR.

Regards,
Marco.

**Comment by tfoote** [comment]
Indeed that's legacy. A PR to clean it up would be appreciated.
