### ISSUE TITLE
create a tool to project camera coordinates

### ISSUE THREAD

**Issue by tfoote** [ros/geometry2#37]
This would be a nice tool to have built on top of tf could project camera pixels with depth into 3d points in space easily.  Originally: https://code.ros.org/trac/ros-pkg/ticket/1656

We now have lots of cameras in the system, and need to project in and out of pixel coordinates. Each imager/camera can be thought of as being in its own frame, which is non-orthogonal and in pixel coordinates. Points from the world can be transformed into this frame using the projection matrix (currently in CamInfo?.msg) with a perspective transform.

Ideally going from 3D points to camera coordinates should be as simple as a TF call. This means that the user will have to publish a new type of message on a topic like "tf_cam_message" or similar:

Header header
string parent_id
PerspectiveTransform transform
For the left-stereo, this would probably be populated as follows:

msg.header.frame_id="stereo_left_rect_frame"
msg.parent_id="stereo_optical_link"
There are definitely some more details that need to be hammered out about disparity, and going up-and-down through the transforms, but this is definitely a start

**Comment by vrabaud** [comment]
This is actually in OpenCV: http://docs.opencv.org/modules/imgproc/doc/geometric_transformations.html#undistortpoints
And as it is not easy to implement (mostly because of distortion), I'd close this issue  and let people use that function.

**Comment by tfoote** [comment]
Yeah, we shouldn't replicate OpenCV's functionality.
