### ISSUE TITLE
no top level LICENSE file

### ISSUE THREAD

**Issue by MarkAtwood** [ros/geometry2#375]
This repo lack a top level LICENSE file
The Apache 2.0 license makes sense for this repo.

**Comment by mm318** [comment]
BSD license has been added with https://github.com/ros2/geometry2/pull/106. This issue may be closed, @MarkAtwood @tfoote.

**Comment by MarkAtwood** [comment]
Thank you. BSD-2 license confirmed.

**Comment by ros-discourse** [comment]
This issue has been mentioned on **ROS Discourse**. There might be relevant details there:

https://discourse.ros.org/t/status-of-os-license-clearing-for-ros2/33753/6
