### ISSUE TITLE
complie error

### ISSUE THREAD

**Issue by zx801** [ros/geometry2#376]
geometry2/tf2_geometry_msgs/include/tf2_geometry_msgs/tf2_geometry_msgs.h:47:10: fatal error: kdl/frames.hpp: No such file or directory
 #include <kdl/frames.hpp>

First time issue not sure how to solve this problem
Many thanks in advance

**Comment by tfoote** [comment]
It's likely that you are missing a dependency, kdl. 

Please ask questions on http://answers.ros.org according to our support policy: http://wiki.ros.org/Support We try to keep the issue tracker reserved for bugs and feature developments.
