### ISSUE TITLE
Error in rosbag play (Transform[sender=unknown_publishser]

### ISSUE THREAD

**Issue by ghost** [ros/geometry2#385]
Dear Altruist people,

When I am trying to play the pointcloud2 topic in the legloam of a pre-recorded bag file with "map" as the fixed frame I am getting an error

![61997955_1103183456543123_1161444094111645696_n](https://user-images.githubusercontent.com/49127638/59026307-55fe5c00-8813-11e9-97e5-ce32108e2013.jpg)

The herewith following picture is the launch file 

![61933099_373225779977389_2693832161252868096_n](https://user-images.githubusercontent.com/49127638/59040921-e5683700-8834-11e9-91d2-582cc664b221.jpg)

The rqt_tf_tree is as the following

![61885174_263192037850450_3706113157865930752_n](https://user-images.githubusercontent.com/49127638/59026474-b9888980-8813-11e9-9e23-dbafd6c08866.jpg)

When I am running rosrun rqt_tf_tree rqt_tf_tree, I am also getting a warning like the following picture-

![62004636_306515476960713_1810894229312897024_n](https://user-images.githubusercontent.com/49127638/59026579-04a29c80-8814-11e9-94bc-892f81ab8369.jpg)

Can you please help me what should I do to resolve this issue ?

Thank you very much for your valuable time.

Thanks 
Ashik

**Comment by tfoote** [comment]
Please ask questions on http://answers.ros.org according to our support policy: http://wiki.ros.org/Support We try to keep the issue tracker reserved for bugs and feature developments.

**Comment by migiuliani** [comment]
Hey guys,
were you able to solve this issue? I have the same problem trying to run Autoware-Carla simulation environment.
Thank you in advance
