### ISSUE TITLE
timestamp error while playing a recorded bag file

### ISSUE THREAD

**Issue by ghost** [ros/geometry2#386]
Hi,

when I am trying to replay the point cloud2 topic from a recorded bag file I am receiving an error like
![image](https://user-images.githubusercontent.com/49127638/59137900-3b2d0400-8947-11e9-8b59-6a7c4c8ef9b5.png)

I have already set up the sim time as true in my launch file but still it's coming up with same error
![image](https://user-images.githubusercontent.com/49127638/59137930-66afee80-8947-11e9-9326-dd0bd0b60186.png)

Anyone has any idea why my bag file is failing to sync with the ros time.

Thanks
Ashik

**Comment by tfoote** [comment]
Please ask questions on http://answers.ros.org according to our support policy: http://wiki.ros.org/Support We try to keep the issue tracker reserved for bugs and feature developments.
