### ISSUE TITLE
Feature request: Manual transform frame manipulation

### ISSUE THREAD

**Issue by rickstaa** [ros/geometry2#410]
First of all, thanks for the amazing tool it really helps me in my robotics projects! There is, however, one useful feature that I'm missing. After needing to manually change my tf2 frames, I stumbled upon this very useful repository [https://github.com/PickNikRobotics/tf_visual_tools](https://github.com/PickNikRobotics/tf_visual_tools) by [@PickNikRobotics](https://github.com/PickNikRobotics). I think incorporating this function in the main package would be very useful.

**Comment by tfoote** [comment]
With the high level dependencies that package relies upon it's not suitable to be merged into the core package. For example it has gui requirements that are not approriate for a low level package. However a contributed tutorial to make the package more visible would be helpful for other users.

**Comment by rickstaa** [comment]
@tfoote Thanks for your response. Good idea, I will make a contributed tutorial if I can get the package to work on melodic ([related to this issue](https://github.com/PickNikRobotics/tf_visual_tools/issues/6)).

**Comment by rickstaa** [comment]
**Update:** As I could not fix the problems I had with the package under ROS melodic I am reluctant to write a contributed tutorial at the moment. I, however, opened an issue might the original authors/maintainers of the package [/tf_visual_tools/issues/7](https://github.com/PickNikRobotics/tf_visual_tools/issues/7) want to write one.

**Comment by artemiialessandrini** [comment]
@rickstaa Good, tool works in melodic now.
[ /tf_visual_tools/issues/6](https://github.com/PickNikRobotics/tf_visual_tools/issues/6)
