### ISSUE TITLE
geometry2/tf2_ros/include/tf2_ros/static_transform_broadcaster.h error and geometry2/tf2_ros/src/static_transform_broadcaster.cpp

### ISSUE THREAD

**Issue by bhushaaan** [ros/geometry2#495]
Cloned this git repo: https://github.com/ros/geometry2/ and while catkin_make got this error, not sure how to solve this as this shows missing files/ improper header files. Please tell me a solution so that i can move ahead with my project with drones and ros kinetic for Ubuntu 16.04 version 

![Screenshot from 2021-02-03 17-53-59](https://user-images.githubusercontent.com/62214456/106746900-2e474300-6649-11eb-8a5a-f8edd47059db.png)
![Screenshot from 2021-02-03 17-54-03](https://user-images.githubusercontent.com/62214456/106746907-30a99d00-6649-11eb-9479-648c2255db1c.png)

**Comment by tfoote** [comment]
As I commented here: https://answers.ros.org/answers/370912/revisions/ please ask your own question on answers.ros.org make sure to provide enough information to 

It's consider poor form to ask multiple times. Also please don't use screenshots but copy and paste the actual text so we can search and copy and replace. Make sure to include enough information to fully reproduce your environment. 

Please see our support guidelines at https://wiki.ros.org/Support
