### ISSUE TITLE
A mistake in tf2/Tutorials

### ISSUE THREAD

**Issue by Mingrui-Yu** [ros/geometry2#517]
In the "Writing a tf2 listener (Python)", the first argument of "lookup_transform" is interpreted as "from this frame", and the second argument is interpreted as "to this frame".

![Writing a tf2 listener (Python)](https://user-images.githubusercontent.com/39028768/130344445-5cf9b213-e539-4482-bc98-d97d6d27d4f0.png)

However, in the "Writing a tf2 listener (C++)", it is reversed.
![Writing a tf2 listener (C++)](https://user-images.githubusercontent.com/39028768/130344483-b190110b-b013-40ae-8ac5-5b416fca0845.png)

According to the Code API, the latter is true. 

Is this a mistake in the tutorials?

**Comment by tfoote** [comment]
No they're correct. This is an unfortunate ambiguity in common language around transforms. The transform from frame A to frame B is the transform which will take data from B to A. This is why the API uses target and source to be explicit about referencing the data source and target.

**Comment by Mingrui-Yu** [comment]
But why are the Python API and C++ API inconsistent? They are completely reversed. @tfoote
