### ISSUE TITLE
tf2_ros: Python documentation missing

### ISSUE THREAD

**Issue by jack-oquin** [ros/geometry2#52]
It looks like there was an attempt to move the Python documentation from the tf2 package to tf2_ros, but that activity was not completed.

The fix is probably not difficult. I notice that `index.rst` is missing and also the rosdoc element in package.xml: 

``` xml
  <export>
    <rosdoc config="rosdoc.yaml" />
  </export>
```

The Sphinx `conf.py` looks wrong, too. If I can find some time, I'll submit a pull request.

**Comment by jack-oquin** [comment]
I still don't see the Python docs on the wiki. Is it waiting for the build farm to update?

**Comment by tfoote** [comment]
the online docs take up to 3 days to refresh. I'll try to accelerate this one
