### ISSUE TITLE
Pose and Transform messages are redundant

### ISSUE THREAD

**Issue by jeanchristopheruel** [ros/geometry2#526]
It is redundant to have both [Transform](https://github.com/ros/geometry2/blob/noetic-devel/tf2/include/tf2/LinearMath/Transform.h) and [Pose](https://github.com/ros/common_msgs/blob/noetic-devel/geometry_msgs/msg/Pose.msg) since they have the same fundamental semantic. tf2 should stop using `Transform` and start using exclusively `Pose`.

Related to [this issue](https://github.com/ros/common_msgs/issues/175).

**Comment by tfoote** [comment]
Closing with https://github.com/ros/common_msgs/issues/175 more info at https://github.com/ros2/common_interfaces/issues/152
