### ISSUE TITLE
sleep_duration of can_transform takes too much time

### ISSUE THREAD

**Issue by KennyRotella** [ros/geometry2#531]
https://github.com/ros/geometry2/blob/fe0457fe0d761a1dcc9182f9cc09912b3a4a8e2d/tf2_ros/src/buffer.cpp#L41

Hello, I want to wait for a transform using 120 seconds of timeout, but right after executing the bag it takes 12 secs to find first transform, is there any method to reduce this period of sleep?

https://github.com/ros/geometry2/blob/fe0457fe0d761a1dcc9182f9cc09912b3a4a8e2d/tf2_ros/src/buffer.cpp#L163

**Comment by tfoote** [comment]
If you're sleeping 12 seconds that sounds like the system is working as expected. That's already 10 cycles of polling. And it polls before sleeping. 

If you want want to try to optimize the extra ~1% polling latency you can work around this by calling the wait with a shorter duration multiple times.
