### ISSUE TITLE
New release for Noetic

### ISSUE THREAD

**Issue by MatthijsBurgh** [ros/geometry2#536]
Sadly no new release was published before the recent Noetic sync.

I think it would be really appreciated by the community when a new release would be published before the next Noetic sync.

**Comment by MatthijsBurgh** [comment]
@tfoote friendly ping

**Comment by MatthijsBurgh** [comment]
@tfoote ping ping ;)

**Comment by MatthijsBurgh** [comment]
@tfoote ping ping ping ;)

**Comment by MatthijsBurgh** [comment]
@tfoote ping ping ping ping ;)

**Comment by MatthijsBurgh** [comment]
@tfoote ping ping ping ping ping ping ;)

**Comment by gavanderhoorn** [comment]
Would it be an idea to add some more people to the release/maintenance team to not have to bother @tfoote with requests like these?

**Comment by MatthijsBurgh** [comment]
@gavanderhoorn sounds like a plan. I have no experience with releasing ROS packages. So would you be open to it?

**Comment by gavanderhoorn** [comment]
I expect @tfoote to respond with "it's much more than just running Bloom: checking PRs, running tests, making sure there are no regressions, keeping track of the direction of development, etc, etc". Which would certainly be the truth.

I'd not be unwilling to contribute some time to "just run Bloom", but I don't want to become just-another-bottleneck for `geometry2` releases / maintenance.

For such a core package though, it would seem prudent to make sure there are sufficient maintainers to at least release things every-now-and-then.

**Comment by MatthijsBurgh** [comment]
@tfoote can we get a new release in before the next sync? https://discourse.ros.org/t/noetic-sync-before-roscon-iros/27646

**Comment by gavanderhoorn** [comment]
Maybe post on that discourse thread?

**Comment by ros-discourse** [comment]
This issue has been mentioned on **ROS Discourse**. There might be relevant details there:

https://discourse.ros.org/t/noetic-sync-before-roscon-iros/27646/3

**Comment by tfoote** [comment]
Sorry for the delay , I will review what's in the branch is releasable and get it out shortly.

**Comment by tfoote** [comment]
Sorry I don't want to push it in right before a sync happens to make sure that we have a good amount of testing it will land right after the sync. https://github.com/ros/rosdistro/pull/34896

However you can test it in the testing/shadow-fixed repo shortly thereafter
