### ISSUE TITLE
Using AngleShortestPath or getAngleShortestPath in python

### ISSUE THREAD

**Issue by ericahellscythe** [ros/geometry2#549]
Hi,

I am trying to find a way to use the AngleShortestPath/getAngleShortestPath function on python but so far I see that it is only available on c++. 

If I am wrong, can someone tell me how to use this function in python?
If not, is there any other alternatives on python or any plans for this to be on python?

Thanks!

**Comment by peci1** [comment]
You are probably looking for the angles library: https://github.com/ros/angles/blob/54ad72b0ce473a2e1d98da447898bf2fcd36519f/angles/angles/__init__.py#L50 .

**Comment by tfoote** [comment]
I"m going to close this as the above pointer appears to be what's needed.
