### ISSUE TITLE
the parameter "time" not used in canTransform？

### ISSUE THREAD

**Issue by zlbing** [ros/geometry2#556]
we found the parameter "time" that not used in canTransform function, how to understand it, maybe is bug?
https://github.com/ros/geometry2/blob/309814fd7d55d874f9bac40b2cc8669a5b86f3c5/tf2_ros/src/buffer.cpp#L120C39-L120C43

**Comment by tfoote** [comment]
Please provide an example of how time is not used. It's passed through to `canTransform` in https://github.com/ros/geometry2/blob/309814fd7d55d874f9bac40b2cc8669a5b86f3c5/tf2_ros/src/buffer.cpp#L135 and https://github.com/ros/geometry2/blob/309814fd7d55d874f9bac40b2cc8669a5b86f3c5/tf2_ros/src/buffer.cpp#L141

It sounds like you might have a question about how things work. As such I'm going to close this and request that you ask your question more fully on https://robotics.stackexchange.com Make sure to provide enough context for people to know what you're trying to do and what is going wrong so they can help you effectively.
